### ISSUE TITLE
VS CODE + DELVE + GLFW V3.2 PROBLEM

### ISSUE THREAD

**Issue by MrLiet** [go-gl/glfw#177]
Hello.

I have compile error:

![image](https://cloud.githubusercontent.com/assets/23429917/20272702/4ff18ac6-aac1-11e6-9e7b-215ac472d93c.png)

Source code:

```
package main

import "github.com/go-gl/glfw/v3.2/glfw"
import "runtime"

func main() {

	runtime.LockOSThread()

	glfw.Init()

	w, _ := glfw.CreateWindow(800, 600, "hello", nil, nil)

	for {
		glfw.PollEvents()
		if w.ShouldClose() {
			break
		}
	}

}
```

Console output:

> me/proj1
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): strdup: not defined
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> github.com/go-gl/glfw/v3.2/glfw(.text): undefined: strdup
> exit status 2
> 

Im use:

- Windows 64 bit
- Go 1.7.3 
- Mingw 64
- VS Code

VS Code settings:
```
{
    "go.buildOnSave": true,
    "go.lintOnSave": true,
    "go.vetOnSave": true,
    "go.buildTags": "",
    "go.buildFlags": [],
    "go.lintTool": "golint",
    "go.lintFlags": [],
    "go.vetFlags": [],
    "go.coverOnSave":false,
    "go.useCodeSnippetsOnFunctionSuggest": true,
    "go.formatOnSave": true, 
    "go.formatTool": "goreturns",
    "go.formatFlags": [],
    "go.gocodeAutoBuild": false,
    "go.autocompleteUnimportedPackages": true
}
```

and Launch settings:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch",
            "type": "go",
            "request": "launch",
            "mode": "debug",
            "program": "${workspaceRoot}",
            "env": {},
            "args": []
        }
    ]
}
```

And it's work fine with glfw 3.1 version
![image](https://cloud.githubusercontent.com/assets/23429917/20272758/7aef4be6-aac1-11e6-8d41-a8a5081817a6.png)

Help!

**Comment by tapir** [comment]
You're probably using and old version of Go.
It was fixed here: https://github.com/golang/go/issues/7555

3.1 works because the Go bug was not fixed by then and we had a workaround in place. It was removed in 3.2.

**Comment by shurcooL** [comment]
@tapir, he said he's using Go 1.7.3, so it's not an old version of Go.

@MrLiet, can you run the following 4 commands and share their output exactly:

```
go version
go env
go get -u -v github.com/go-gl/glfw/v3.1/glfw
go get -u -v github.com/go-gl/glfw/v3.2/glfw
```

If that prints the same error about `strdup` being undefined for 3.2 only, it might be that we messed up some import in the headers on Windows. Can anyone else confirm if 3.2 works on Windows for them?

**Comment by MrLiet** [comment]
@tapir @shurcooL  Thx for answer!

>go version

`go version go1.7.3 windows/amd64`

>go env

```
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Workplace\GO
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\User\AppData\Local\Temp\go-build646474422=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
```
>go get -u -v github.com/go-gl/glfw/v3.1/glfw

`github.com/go-gl/glfw (download)`

glfw v3.1 workifine
glfw v3.2 also output

>go get -u -v github.com/go-gl/glfw/v3.2/glfw

`github.com/go-gl/glfw (download)`

glfw v3.2 also output

**Comment by tapir** [comment]
Oh I didn't see you were using 1.7.3
I've tested the example code you provided and it doesn't give any errors on my computer which consists of
* Go 1.7.3
* Windows 7 64 bit
* MSYS2 Mingw64

**Comment by shurcooL** [comment]
If the only output from `go get -u -v github.com/go-gl/glfw/v3.2/glfw` was `github.com/go-gl/glfw (download)`, that means it compiled the package successfully. At least in your terminal.

That suggests there's something wrong only when trying to build inside VSCode specifically.

**Comment by MrLiet** [comment]
![image](https://cloud.githubusercontent.com/assets/23429917/20339929/86692522-ac11-11e6-8ca6-6d781fef0a3c.png)

But if compile with `buildFlags": "-ldflags '-linkmode=external'`
Then i have console output: `could not launch process: Could not determine version number: could not find symbol value for runtime.buildVersion`

Look like delve error

**Comment by tapir** [comment]
Try to run it with `go run entry.go` if it doesn't give any errors you should report it to delve or vscode-go

**Comment by MrLiet** [comment]
https://github.com/derekparker/delve/issues/670#issuecomment-260881260
