### ISSUE TITLE
v3.3/glfw: binaries built for FreeBSD links against shared libglfw.so.3

### ISSUE THREAD

**Issue by Jacalz** [go-gl/glfw#313]
During some FreeBSD testing of [wormhole-gui](https://github.com/Jacalz/wormhole-gui) (uses this project through [Fyne](https://github.com/fyne-io/fyne)), I noted that running FreeBSD binaries (both those compiled from Linux and those compiled on FreeBSD) linked dynamically against a shared `libglfw.so.3`. This means that running the binaries without first installing glfw with `pkg install glfw` resulted in the following error:
```
ld-elf.so.1: Shared object "libglfw.so.3" not found, required by "wormhole-gui"
```

This was quite unexpected given that every other platform seems to be linking statically against it and does not require installing glfw in any way to run the binaries. I thus opened a bug for this for Fyne (see https://github.com/fyne-io/fyne/issues/1928), but I don't know how much we can do to fix this, so I decided to open the issue here as well to inform you guys.

**Comment by pwaller** [comment]
Thanks for the note. I agree it's weird.

Seems this was a mistake introduced in https://github.com/go-gl/glfw/pull/233. Happy to review PRs to change the situation but don't have a freebsd system to test on, so help wanted to fix this.

Ping @neilpa who made the change and @hajimehoshi @tapir who also looked at it. Other than making the build work I guess there was not much rational behind using pkg-config?

**Comment by Jacalz** [comment]
I tried to get this working when cross-compiling to FreeBSD on Linux but couldn't quite figure out what was wrong. Reverting the mentioned commit above just leads to the following error (which is weird, `-lX11` is already in the linker flags):
```
# github.com/go-gl/glfw/v3.3/glfw
In file included from vendor/github.com/go-gl/glfw/v3.3/glfw/c_glfw.go:4:
In file included from ./glfw/src/context.c:30:
In file included from ./glfw/src/internal.h:188:
./glfw/src/x11_platform.h:33:10: fatal error: 'X11/Xlib.h' file not found
#include <X11/Xlib.h>
         ^~~~~~~~~~~~
```
I think someone more familiar with FreeBSD and the glfw build flags need to have a look at this.

**Comment by xorander00** [comment]
@Jacalz I just ran into this error as well. From a quick, initial look at the error message you just posted above, it seems like /usr/local isn't being included in the search paths for CC. If that's the case, then it's likely also the case for the linker path.  
  
I'm currently compiling & installing graphics/glfw to try the application, will take a peek at the source later if I can catch a few minutes :)

**Comment by hajimehoshi** [comment]
https://github.com/go-gl/glfw/blob/81c96020f6ea59eb894a253b9f5e7dc729a00a44/v3.3/glfw/build.go#L44

Now there is `pkg-config` for `glfw3`. I started to think this is weird.

EDIT: @tapir already pointed this out https://github.com/go-gl/glfw/pull/233#issuecomment-446863612. So we should fix the current pkg-config options not to use external glfw3 directly.
