### ISSUE TITLE
Cant run the hello world demo on windows

### ISSUE THREAD

**Issue by moon004** [go-gl/glfw#236]
```
go env
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\SiangHwa\AppData\Local\go-build
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\Sianghwa\golang
set GOPROXY=
set GORACE=
set GOROOT=C:\Go
set GOTMPDIR=
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\SiangHwa\AppData\Local\Temp\go-build483450046=/tmp/go-build -gno-record-gcc-switches
```
```
go version
go1.11 windows/amd64
```
```
gcc --version
gcc (x86_64-posix-sjlj-rev0, Built by MinGW-W64 project) 8.1.0
```

When i try to run the hello world demo from the description i got the following error message:
```
C:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:\Users\SiangHwa\AppData\Local\Temp\go-link-961526691\000002.o: In function `glfwSwapBuffers':
E:\Sianghwa\golang\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/context.c:609: undefined reference to `__assert_func'
C:\Users\SiangHwa\AppData\Local\Temp\go-link-961526691\000002.o: In function `glfwExtensionSupported':
E:\Sianghwa\golang\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/context.c:642: undefined reference to `__assert_func'
C:\Users\SiangHwa\AppData\Local\Temp\go-link-961526691\000002.o: In function `glfwGetProcAddress':
E:\Sianghwa\golang\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/context.c:707: undefined reference to `__assert_func'
C:\Users\SiangHwa\AppData\Local\Temp\go-link-961526691\000002.o: In function `glfwGetInputMode':
E:\Sianghwa\golang\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/input.c:153: undefined reference to `__assert_func'
C:\Users\SiangHwa\AppData\Local\Temp\go-link-961526691\000002.o: In function `glfwSetInputMode':
E:\Sianghwa\golang\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/input.c:174: undefined reference to `__assert_func'
C:\Users\SiangHwa\AppData\Local\Temp\go-link-961526691\000002.o:E:\Sianghwa\golang\src\github.com\go-gl\glfw\v3.2\glfw/glfw/src/input.c:262: more undefined references to `__assert_func' follow
collect2.exe: error: ld returned 1 exit status```

But if i use older version (github.com/go-gl/glfw/v3.1/glfw) instead of (github.com/go-gl/glfw/v3.2/glfw), everything runs well. Is it the latest version doesnt fully work well on windows yet? or am i doing something wrong here?

Thank you in advance for your time and attention. 😄

**Comment by tapir** [comment]
Probably something wrong with your gcc installation.
As seen in the error it can't find `__assert_func`

**Comment by moon004** [comment]
i have tried different version of msys including 4.8.1, but still it doesn't work, does anyone got it works on windows? How do u set up your environment?

**Comment by tapir** [comment]
Yes it does work in Windows. Though I don't know how you've setup your gcc stack so I won't be of help.
MSYS2 never gave me any problems so far. I think it's the only sane gcc distribution for Windows.

**Comment by moon004** [comment]
@tapir , i would like to know how do u set up your MSYS2 so that it works on glfw v3.2. I would really really  appreciate your effort.

**Comment by tapir** [comment]
Sorry it might be a while since I'm fully occupied by my day job

**Comment by tapir** [comment]
Here is what I did on a fresh virtual machine windows 10 64-bit

* Install msys2 and start msys2-64 terminal
* pacman -Syu
* restart msys2-64 terminal
* pacman -Syu
* pacman -S git mingw-w64-x86_64-gcc mingw-w64-x86_64-go
* restart msys2-64 terminal
* go get github.com/go-gl/glfw/v3.2/glfw

it seems to build OK
