### ISSUE TITLE
Unable to go get glfw v3.2

### ISSUE THREAD

**Issue by codephobia** [go-gl/glfw#179]
Trying to use the following command ends up just returning an error, but works for v3.1.

Command:
`go get -u github.com/go-gl/glfw/v3.2/glfw`

Error:
```
# github.com/go-gl/glfw/v3.2/glfw
In file included from ./glfw/src/internal.h:167:0,
                 from ./glfw/src/context.c:28,
                 from ..\..\go-gl\glfw\v3.2\glfw\c_glfw.go:4:
./glfw/src/win32_platform.h:70:20: fatal error: dinput.h: No such file or directory
compilation terminated.
```

**Comment by dmitshur** [comment]
This looks very similar to #167. Can you check if that's it?

**Comment by codephobia** [comment]
The file seems to be there...

`C:\gopath\src\github.com\go-gl\glfw\v3.2\glfw\glfw\deps\mingw\dinput.h`

**Comment by codephobia** [comment]
I moved the 3 files from the deps folder `go-gl\glfw\v3.2\glfw\glfw\deps\mingw\` to the main folder `go-gl\glfw\v3.2\glfw` and then it was able to build with v3.2.

**Comment by dmitshur** [comment]
Oh, I didn't realize we had a copy of `dinput.h` in the tree. Perhaps we should update the include directories to look there.

I've never looked at this because I don't use Windows at this time.

**Comment by tapir** [comment]
Hmm, what gcc and go environment do you use? On my system (win7 64bit, msys2-64) I don't get such error.

**Comment by codephobia** [comment]
Win10 64bit, go version go1.7.3 windows/amd64, gcc 5.3.0-3 installed using MinGW Installation Manager.

**Comment by tapir** [comment]
I wonder if a `-Iglfw/deps/mingw` in build.go work?

**Comment by codephobia** [comment]
I tried to build my code on another machine, and it seems I am getting this error again, but this time I can't seem to be able to resolve it.

**Comment by codephobia** [comment]
Oh, it looks like my go version was a little out of date. Updating to latest version resolved the issue.

**Comment by dmitshur** [comment]
> but this time I can't seem to be able to resolve it.

> Updating to latest version resolved the issue.

Do you mean the _original_ issue is completely resolved now, or the _new_ one you just ran into recently?

Did you still have to move some files in the repo manually for it to work?

**Comment by nxtlvlgg** [comment]
I still had to move files, but 1.6.x wouldn't find the files even when I copied them. Upgrading to 1.7.4 solved that issue.

**Comment by codephobia** [comment]
I still had to move files, but 1.6.x wouldn't find the files even when I copied them. Upgrading to 1.7.4 solved that issue.

**Comment by dmitshur** [comment]
I see, so the original issue still stands.

Have you had a chance to try the suggestion in https://github.com/go-gl/glfw/issues/179#issuecomment-269600093?

**Comment by codephobia** [comment]
> I wonder if a -Iglfw/deps/mingw in build.go work?

I'm not sure what exactly I'm supposed to be doing to test that. Import the folder with the following?

```
import (
    "github.com/go-gl/glfw/v3.2/glfw/glfw/deps/mingw"
)
```

I'm assuming not since there is no go code in there.

**Comment by dmitshur** [comment]
Instead of moving those header files, try opening the [`v3.2/glfw/build.go` file](https://github.com/go-gl/glfw/blob/6e7202f2d691ed1d79bcdaed6cce0061006ce565/v3.2/glfw/build.go#L7) in your local GOPATH workspace and edit line 7 from:

```
#cgo windows CFLAGS: -D_GLFW_WIN32
```

To:

```
#cgo windows CFLAGS: -D_GLFW_WIN32 -Iglfw\deps\mingw
```

That's where cgo compiler flags for Windows platform are being specified.

**Comment by codephobia** [comment]
Yep that totally works. No need to copy the files with that added. So the initial get still fails since it can't build, but then add that line, and run the get again and it builds properly.

**Comment by dmitshur** [comment]
Makes sense.

We can fix the initial build not working by merging that change into `master`. Would you like to make a PR?

I won't be able to review it well because I don't know Windows cgo details, but hopefully someone else can. I don't have objections because adding that include directory seems harmless; I just don't know if there's perhaps a better (more direct) fix.
